jobname: esm-piNoCrops
queue: normal
walltime: 3:10:00
storage: # For me, payu couldn't properly recognise that p66 is needed. I've added it here.
    gdata:
        - access
        - hh5
        - p66
    scratch:
        - p66

# note: if laboratory is relative path, it is relative to /scratch/$PROJECT/$USER
laboratory: access-esm
model: access

submodels:
    - name: atmosphere
      model: um
      ncpus: 192
      exe: /g/data/access/payu/access-esm/bin/coe/um7.3x
      input:
        - /g/data/access/payu/access-esm/input/pre-industrial/atmosphere
        - /g/data/access/payu/access-esm/input/pre-industrial/start_dump

    - name: ocean
      model: mom
      ncpus: 180
      exe: /g/data/access/payu/access-esm/bin/coe/mom5xx
      input:
        - /g/data/access/payu/access-esm/input/pre-industrial/ocean/common
        - /g/data/access/payu/access-esm/input/pre-industrial/ocean/pre-industrial

    - name: ice
      model: cice
      ncpus: 12
      exe: /g/data/access/payu/access-esm/bin/coe/cicexx
      input:
        - /g/data/access/payu/access-esm/input/pre-industrial/ice

    - name: coupler
      model: oasis
      ncpus: 0
      input:
        - /g/data/access/payu/access-esm/input/pre-industrial/coupler

collate:
   exe: /g/data/access/payu/access-esm/bin/mppnccombine
   restart: true
   mem: 4GB

restart: /g/data/access/payu/access-esm/restart/pre-industrial

calendar:
    start:
        year: 101
        month: 1
        days: 1

    runtime:
        years: 1
        months: 0
        days: 0

runspersub: 1

userscripts:
    # Setup land-use changes.
    setup: ./scripts/pre.sh /g/data/p66/tfl561/sensitivity_lu_map/1850_no_humans_CABLE_fraction.nc

stacksize: unlimited

qsub_flags: -W umask=027
