format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-piNoCrops/restart068/atmosphere/restart_dump.astart
  hashes:
    binhash: 2976c9b59dcfaa5cde38879958df329b
    md5: ddd98db31d38ede0b5d3a3d4a09b74c4
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-piNoCrops/restart068/atmosphere/um.res.yaml
  hashes:
    binhash: cc7e2181f34e8a0dc87aa341193f3d83
    md5: d1538a862bac4481ae3a5c6e0763e812
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-piNoCrops/restart068/coupler/a2i.nc
  hashes:
    binhash: b09204c2ac1b724cf27328432607136e
    md5: 2ebb3e5690cfc5c1a835a8d851733131
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-piNoCrops/restart068/coupler/i2a.nc
  hashes:
    binhash: 4e4cd5773d528507b69b17a068591bd4
    md5: b8c48895acf2047505968ad754f5d350
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-piNoCrops/restart068/coupler/o2i.nc
  hashes:
    binhash: 03c9471726cc9deb828e28befe9a11ab
    md5: 1963c96d1b70afb8297ae40d809d803c
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-piNoCrops/restart068/ice/cice_in.nml
  hashes:
    binhash: c3c6ece1c98b0d4face05c93eaec2ad1
    md5: 333bae2e0fc5a9fdcee8cfdf2c38e22e
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-piNoCrops/restart068/ice/ice.restart_file
  hashes:
    binhash: 7ccbe12e4109eb0138b13886d7b7ca76
    md5: 7e154b9d7b079e5efa261d5aaccc4d89
work/ice/RESTART/iced.01680201:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-piNoCrops/restart068/ice/iced.01680201
  hashes:
    binhash: 72bbe9e64c547040058cf6a5d5739fc5
    md5: 0bf384bb8f19addbbcdcd3a3feb8d6f3
work/ice/RESTART/iced.01680301:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-piNoCrops/restart068/ice/iced.01680301
  hashes:
    binhash: c3fe00fcd5632ca9f2ccff74fd7b272a
    md5: caa1af9d383ca7fc70cef3660a322edc
work/ice/RESTART/iced.01680401:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-piNoCrops/restart068/ice/iced.01680401
  hashes:
    binhash: 4185bba3efaff3bb1f6e39c80232a886
    md5: c06344ba67f2ba8a52631af0c0df632c
work/ice/RESTART/iced.01680501:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-piNoCrops/restart068/ice/iced.01680501
  hashes:
    binhash: 170149ee3412e165dd804e54e6a71144
    md5: 398ab6d3b51e10effa958b4b7a36da31
work/ice/RESTART/iced.01680601:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-piNoCrops/restart068/ice/iced.01680601
  hashes:
    binhash: e39e6deab6015473447bcea95f99db46
    md5: f10b8267130617564cd47b50d4c2b19e
work/ice/RESTART/iced.01680701:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-piNoCrops/restart068/ice/iced.01680701
  hashes:
    binhash: 0c51603498a0e290c4b0c2731262c7eb
    md5: dafae18662d28a6677aca5f903b4f946
work/ice/RESTART/iced.01680801:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-piNoCrops/restart068/ice/iced.01680801
  hashes:
    binhash: 95aa21f248ef7104e0a94480fed87188
    md5: eca9c942621e14d07fb9ca292c58fce5
work/ice/RESTART/iced.01680901:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-piNoCrops/restart068/ice/iced.01680901
  hashes:
    binhash: d0d5bb73e96e0166739a527e74e4ae24
    md5: 6ee7c9c8679601165ead26d9ae7103fa
work/ice/RESTART/iced.01681001:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-piNoCrops/restart068/ice/iced.01681001
  hashes:
    binhash: 96aa1b9fb62882c71fddd933326ec665
    md5: 2fa97d46188af33c8b62c6a1cdc027df
work/ice/RESTART/iced.01681101:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-piNoCrops/restart068/ice/iced.01681101
  hashes:
    binhash: 66b9cd844d267c763e290f631150260f
    md5: bd6d1b5c1713f8496f1a4bbcc7dafdf5
work/ice/RESTART/iced.01681201:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-piNoCrops/restart068/ice/iced.01681201
  hashes:
    binhash: df411d17e8c49a44c9017cb82e4b5437
    md5: f738ca8f029a44c423d6804ca4db4490
work/ice/RESTART/iced.01690101:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-piNoCrops/restart068/ice/iced.01690101
  hashes:
    binhash: 6fb3fb5f18311d5aec648fd5e854ad96
    md5: 21bd45554c42ee98f0c16f83b6cd6762
work/ice/RESTART/input_ice.nml:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-piNoCrops/restart068/ice/input_ice.nml
  hashes:
    binhash: c495135b9758acc847b4b83beaca5fc6
    md5: b7e297f127034f73e2ad7f09792659ba
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-piNoCrops/restart068/ice/mice.nc
  hashes:
    binhash: 22b9f307179866ee46043756f946de9d
    md5: 021d898c9a13dd99b692bd17ccf42c51
work/ocean/INPUT/csiro_bgc.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-piNoCrops/restart068/ocean/csiro_bgc.res.nc
  hashes:
    binhash: a3bfff3b971d42af2fa552abeb10310c
    md5: 42d8050517eae2a6e47f28cd21b60567
work/ocean/INPUT/csiro_bgc_sediment.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-piNoCrops/restart068/ocean/csiro_bgc_sediment.res.nc
  hashes:
    binhash: 25add793c63f52f3bdd0bf3ab188da9d
    md5: 740bceb86ac46d32da44f65f15c9e539
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-piNoCrops/restart068/ocean/ocean_age.res.nc
  hashes:
    binhash: 160c4a2a73bb2ab4f355b72d2786c4e4
    md5: cb1ef5dfebae4c791309e0f34b4ba0a1
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-piNoCrops/restart068/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: edf4374c7783f18e57f40495a1a5070b
    md5: 41d14d12bffbcb6089ddba03e20df524
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-piNoCrops/restart068/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: eb9657e4d52e3355eacc7af17c16a473
    md5: 5bd26e66b5ed4d74992ee45469f65e8c
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-piNoCrops/restart068/ocean/ocean_density.res.nc
  hashes:
    binhash: beb45cef10fd683c11bd9e9f9f2cfbd4
    md5: 71e10db6cb9fc3b1bce65b0858141656
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-piNoCrops/restart068/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 02a4548f9e6004ea9582f86332b84314
    md5: 7e6bcaee5bc5435e23de757afe256645
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-piNoCrops/restart068/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 816759650ea2413ac4e09575291f23e7
    md5: 082c1b0ddfcf8f4ad9712a74823c6ce3
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-piNoCrops/restart068/ocean/ocean_neutral.res.nc
  hashes:
    binhash: c78ec9e9f9606fc8664af8fcd90a3dbb
    md5: af9c5ddfdf114f0fe4e32fb873bb3308
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-piNoCrops/restart068/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: b59fc813b820373e6620e7d22db5eddd
    md5: b43bade9850dd611f73a4ca5956b8e03
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-piNoCrops/restart068/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 6c860b48b290103c98fe0045c79a8668
    md5: fdfbf03017e47f8127edc65698255792
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-piNoCrops/restart068/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: fda66e097c3caf347d587e319d0dc60d
    md5: fe527a9917d30955d0dc082271c1392f
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-piNoCrops/restart068/ocean/ocean_solo.res
  hashes:
    binhash: 3aba85b5fe8254b4b58db99d7db40e61
    md5: 2a7a6aa126b8239802cf8bbdb1891941
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-piNoCrops/restart068/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: b92106ed0805e105e5dcbeb38826b827
    md5: 6962124f250e02ce66144604eee93541
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-piNoCrops/restart068/ocean/ocean_thickness.res.nc
  hashes:
    binhash: a6a7798901747e501c0235eea09accd7
    md5: fc8df2bfa7cd6b2aa2f99015208658e6
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-piNoCrops/restart068/ocean/ocean_tracer.res
  hashes:
    binhash: 007d9897f5ed2521eaa25d5e8ec89582
    md5: d76107ad96e416c2def2173f812e1a65
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-piNoCrops/restart068/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 332c265290f8a4ee11de7a862975f96f
    md5: 044c5b754e17235b0d7bb729f9dab562
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-piNoCrops/restart068/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 7a153adafc6863e53a41e69afe026e1b
    md5: 1916189dbeef451e2737f0dc4967b512
